name = "Create Stellar Expanded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60286f9d9a1e557aec06418a4bdad13a4cde452b059954a9bcb93bcdf18457ea"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
