name = "Create Stellar Expanded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0f63001d2993f962970a9c8f0f42744a16b0507e5a2df5590ab17caa3a37bf"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
