name = "Create Stellar Expanded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd4bbaa7bbee0be70fb5cd82ad6ced02c69df594c7a6f446a31261b8e8c56158"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
