name = "Create Stellar Expanded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f0d9aadb735fa66073bffabd0083774cb0ac3bb9973bc90868ea080ff66222"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
