name = "Create Stellar Expanded"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55e89af31343d215764b6780a9d62b2e0af3b07f5ae49e081207bf2e1c7ed79a"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
